### ISSUE TITLE
Analyze the set of metrics again and add new ones if necessary

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#242]

**Comment by ikopylov** [comment]
We have to add hardware metrics. They should be updated in background with large update interval (~1-2m). 
Important hardware metrics:
1. Total disk space on all disks available to Bob
2. Free disk space on all disks available to Bob
3. Total RAM size
4. Free RAM
5. Number of file descriptors in use
6. CPU load

If it is possible with current metrics library, it would be great to add `rate` metrics (`put_rate`, `get_rate`, ...) that measures number of operations per second. 

I suggest to add `put_bytes` and `get_bytes` metrics into `pearl` section to track written data in bytes and read data in bytes.

To make it easier to understand, it is worth to rename section `grinder` to `cluster_grinder`. 

Inside `backend/disks` every disk should be a section and inside that section the `status` metric should be placed. Additionally, I suggest to add `blob_count` metric inside every disk. Both `status` and `blob_count` can be updated in background with large update interval (like hardware metrics).

**Comment by ikopylov** [comment]
It is extremely important to track corrupted BLOB count. Currently, all corrupted BLOBs are moved to a separate directory, so the initial value should be set to the number of BLOBs in that directory and later be updated at runtime.

**Comment by Justarone** [comment]
@ikopylov 

Metrics with disks statuses are already implemented (They were implemented during implementation of `DiskController`). Per disk blob_count also doesn't sound difficult, I'll solve that. `put_bytes` and `get_bytes` metrics are also pretty straightforward to implement.

I have only one question: 
Shortly: Do we really need `rate` metrics?

Detailed: we've moved from [dipstick](https://github.com/fralalonde/dipstick) to [metrics](https://github.com/metrics-rs/metrics), because dipstick doesn't allow to use constantly incrementing counter out of the box (it flushes counters after flush of all metrics, so that's some kind of "rate"). So in metrics we've implemented graphite exporter ourselves and have made constantly growing counters.
I am not sure, that there is a nice (simple) way of doing `rate` metrics with existing code, so we need to rethink, why we can't use some functions on server, which collects metrics (__derivative()__ for constantly growing metrics **or** __integral()__ for "rate" metrics (to get constantly growing counters))

I'll think about that... I have some solutions for our graphite exporter (we can send for every counter `value` and `rate` where `rate = new_value - old_value`, and seems like we won't have many changes), but we'll also need to patch prometheus exporter, and I'm not sure that it's worth doing that instead of aggregation functions on graphite/prometheus.

**Comment by Justarone** [comment]
I am a little bit confused about `total` metrics. Do I understand right that `total` for ram memory for example means how much memory is occupied on the server (i.e. _used_) at the moment or it's just constant value (available ram on server)?
@ikopylov
