### ISSUE TITLE
Write a description on Docker Hub

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#317]
Link to docker hub: https://hub.docker.com/r/qoollo/bob

Required parts:
1. Bob description (can be taken from Readme)
2. Link to GitHub repository
3. Link to Wiki on GitHub
4. Versions description (8 bytes key vs 16 bytes key, alpine vs ubuntu). If key size is not specified it is 8 bytes, if target platform is not specified it is alpine, `latest` - latest release
5. How to use the image. Command to run it (`docker run` with parameters), exposed [ports](https://github.com/qoollo/bob/blob/master/dockerfiles/alpine/Dockerfile#L101) (`22` - ssh,  `80` - [rest api](https://github.com/qoollo/bob/wiki/REST-API), `20000` - [client port](https://github.com/qoollo/bob/wiki/gRPC-API)) and [directories](https://github.com/qoollo/bob/blob/master/dockerfiles/alpine/Dockerfile#L75) (`/bob/log` for log files, `/bob/data` for data, `/bob/configs` for configs), ulimit
6. Configuration details. List of configuration files (`node.yaml`, `cluster.yaml`, `logger.yaml`), their purpose, links to examples in this repository ([node.yaml](https://github.com/qoollo/bob/blob/master/config-examples/node.yaml), [cluster.yaml](https://github.com/qoollo/bob/blob/master/config-examples/cluster.yaml), [logger.yaml](https://github.com/qoollo/bob/blob/master/config-examples/logger.yaml)) and to description in Wiki ([node.yaml](https://github.com/qoollo/bob/wiki/Bob-config), [cluster.yaml](https://github.com/qoollo/bob/wiki/Cluster-config))

Source of inspiration: https://hub.docker.com/r/yandex/clickhouse-server

**Comment by vikhotin** [comment]
Will do

**Comment by vikhotin** [comment]
Attached file is the first suggestion for Bob Docker Hub Bob description.

[Bob.md](https://github.com/qoollo/bob/files/7244362/Bob.md)

**Comment by vikhotin** [comment]
# What is Bob?

Bob is a distributed storage system designed for byte data e.g. photos. It has decentralized architecture where each node can handle user calls.

Source code can be accessed at [https://github.com/qoollo/bob/](https://github.com/qoollo/bob/).

For current documentation, see [https://github.com/qoollo/bob/wiki/](https://github.com/qoollo/bob/wiki/).

# Versions

Images are defined by two characteristic features:

1. Size of the key. Image tags that contain &quot;key8&quot; point to images working with 8 bytes keys, ones that contain &quot;key16&quot; point to images working with 16 bytes keys. Images with unspecified key in tag work with 8 bytes keys.
2. Linux distribution used by image. Image tags can contain &quot;alpine&quot; or &quot;ubuntu&quot; pointing to corresponding distributions. Images with unspecified distribution in tag work on Alpine Linux.

# How to use this image

To start bob instance with docker use the following command:

    docker run –d --ulimit nofile=262144:262144 -v CONFIG_DIR:/bob/configs -v DATA_DIR:/bob/data -v LOG_DIR:/bob/log qoollo/bob cluster.yaml node.yaml

`--ulimit` nofile parameter is highly recommended because Bob can work with a very large number of files, so it may require more open files than default value.

`cluster.yaml node.yaml` are configuration files names you can pass to launch Bob with given configurations. Default names are cluster.yaml and node.yaml.

Bob docker image exposes the following ports:

- 22 – SSH
- 80 – REST API (description provided here: [https://github.com/qoollo/bob/wiki/REST-API](https://github.com/qoollo/bob/wiki/REST-API))
- 20000 – client port (description provided here: [https://github.com/qoollo/bob/wiki/gRPC-API](https://github.com/qoollo/bob/wiki/gRPC-API))

Bob docker image creates the following directories:

- /bob/log for log files
- /bob/data for data
- /bob/configs for configs

You may need to mount these directories on your host filesystem directories using `-v` parameters as shown in the docker run command above:

# Configuration details

Bob requires the following configuration files:

- node.yaml – node configuration file. Example [here](https://github.com/qoollo/bob/blob/master/config-examples/node.yaml), format description [here](https://github.com/qoollo/bob/wiki/Bob-config)
- cluster.yaml – cluster configuration file. Example [here](https://github.com/qoollo/bob/blob/master/config-examples/cluster.yaml), format description [here](https://github.com/qoollo/bob/wiki/Cluster-config)
- logger.yaml – logger configuration file. Example [here](https://github.com/qoollo/bob/blob/master/config-examples/logger.yaml)

**Comment by ikopylov** [comment]
Thanks, that's great!

Minor notes:
1. Extend `Images are defined by two characteristic features:` to `Bob docker images are defined by two characteristic features:`
2. You forgot add information about `latest` tag in `Version` section (it is the latest release including `alpha` releases)
3. In `Bob docker image creates the following directories:` instead of `creates`  it is better to write `uses`

**Comment by vikhotin** [comment]
Fixed!
[Bob.md](https://github.com/qoollo/bob/files/7260826/Bob.md)

**Comment by ikopylov** [comment]
Has added this description to Docker Hub (https://hub.docker.com/r/qoollo/bob). Thanks!
